github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: [
    "https://raw.githubusercontent.com/MikeNoBug/json-web-ext/main/assets/context-menu-demo.gif",
  ] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
